# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json
gui:
    skipDiscardChangeWarning: true
    nerdFontsVersion: "3"
    authorColors:
        "Akshay Aurora": "#ff7eb7"
