# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json
gui:
    skipDiscardChangeWarning: true
    nerdFontsVersion: "3"
    scrollHeight: 50
    authorColors:
        "Akshay Aurora": "#ff7eb7"
git:
    paging:
        colorArg: always
        pager: delta --dark --paging=never
