# Disable the AWS module; it's noisy
[aws]
disabled = true

[gcloud]
disabled = true

[git_state]
disabled = true

[git_status]
disabled = true

[nodejs]
disabled = true

[python]
disabled = true

[character]
vicmd_symbol = "[N](bold blue)"
# vicmd_visual_symbol = "[V](bold blue)"
# vicmd_replace_symbol = "[R](bold blue)"
# vicmd_replace_one_symbol = "[R1](bold blue)"


